### ISSUE TITLE
Optional $mount?

### ISSUE THREAD

**Issue by robokozo** [jackmellis/vuenit#4]
Could calling $mount be optional?

I just want to test some methods in my vue component and I'm using a UI Component library which I haven't figured out how to test-around yet. (Unknown custom element: <el-table> etc) 

Before finding vuenit, I was just not calling out to $mount to prevent Vue from worrying about the template code.

**Comment by jackmellis** [comment]
Interestingly I was actually thinking if going the opposite direction and having an option to remove all custom components so that you're only testing the current component. If you use the production vue.min.js file it supresses these warnings.

That said, having a mount flag would be an easy addition....

**Comment by jackmellis** [comment]
Quick example of how this would work:
```javascript
var vm = vuenit.component(x, { mount : false });
vm.$mount();
```
an issue with this is that vuenit wraps the component in a dummy component, so the child component isn't actually created until the parent is mounted, and I don't think you can mount the parent and not the child...

**Comment by robokozo** [comment]
If you had another solution in mind, it might be worth still exploring. One of the problems with an optional mount flag is that if you wanted to do some testing against the virtual dom, you won't be able to. 

`expect(vm.$el.querySelector('input').disabled).toBe(true);`

An ideal solution would be to mock all 'child components' (even defined globally) to another html tag.

**Comment by jackmellis** [comment]
How about a stubbed components option? Would something like that be useful?
```javascript
vuenit.component(c, {
  components : {
    myChildComponent : '<div/>'
  }
});
```
This way, you'll still end up with a valid component with valid DOM elements inside it that you can assert upon, but you don't have to factor in the logic and setup requirements of your child components.

**Comment by jackmellis** [comment]
Might be able to leverage something similar to this to prevent the component from mounting:  
https://forum.vuejs.org/t/prevent-a-components-lifecycle-from-completing/8797/8  
though calling `mount` at a later point would require even more trickery I suspect...

**Comment by robokozo** [comment]
Yeah I think something like this would be very useful. How do you think that you'd configure globally defined components or installed components like those offered by

https://vuematerial.github.io/#/  or http://element.eleme.io/#/en-US

Consider this page:

```
<template>
    <div>
        <local-component-stub-me></local-component-stub-me>

        <local-component></local-component>

        <md-button @click.native="toggle">Vue-Material Button (Globally Defined)</md-button>

        <input :disabled="disabled" type="text">
    </div>
</template>


<script>

    import LocalComponent_DontCareToTest from './blah/LocalComponent.vue';
    import LocalComponent from './blah/LocalComponent2.vue';

    export default {
        data(){
            return {
                disabled: true
            }
        },
        components: {
            "local-component-stub-me": LocalComponent_DontCareToTest,
            "local-component": LocalComponent
        },
        methods :{
            toggle(){
                this.disabled = !this.disabled;
            }
        }
    };

</script>
```

The test could be setup like this:

```
import VueMaterial from 'vue-material';

vuenit.component(c, {
  stubComponents: {
    "local-component-stub-me":  "<div/>"
  },
 installThings(Vue){
    Vue.use(VueMaterial.mdCore)
    Vue.use(VueMaterial.mdButton)
}
});
```

This way I could check against the virtual dom for the` <input>`, the `<md-button>`, and the `<local-component>` but `<local-component-stub-me>` would be rendered as a div to be tested independently on its own.

**Comment by jackmellis** [comment]
1. I like the idea of the install method - this would allow you to configure the Vue class without polluting the global Vue.  
2. stubComponents is pretty much what I had in mind. So if you stub it, it'll use the mocked value, otherwise it'll look for the original one.  
3. It'd be good if you could stub everything (i.e. `stubComponents : true` or `stubComponents : '<div/>'`).  

The thing is, we're starting to get opinionated here which I'm trying to avoid as much as possible. I don't want to force a particular testing pattern. Some people (like me) would want to stub *everything* that isn't the direct component. Other people will want a component with all of its child components up and running in their tests. Then others (okay, most people) want to mock some stuff but not others.

so:  
The above example follows the *stub these with specific elements but everything else is real*  
I would also like to be able to say *these are real but everything else is stubbed*  
I would *also* like to be able to say *these are real, these are stubbed with specific elements, and everything else is stubbed*  

...perhaps I'm overthinking this

**Comment by jackmellis** [comment]
Okay, pretty simple solution in the end I think:
```javascript
vuenit.component(c, {
  components : { // stub specific components
    replaceMe : '<span></span>'
  },
  stubComponents : true || false || '<div/>' // stub all other components
});
```
so `components` allows you to stub a specific component, it will probably also allow you to provide a full definition object with props etc. if you need a slightly more featured stub. Everything else will be *real*.  
`stubComponents` then determines whether any other components not specified by `components` should be stubbed.

**Comment by robokozo** [comment]
Sounds great :) I look forward to this! 👍

**Comment by jackmellis** [comment]
@robodude  https://github.com/jackmellis/vuenit/releases/tag/0.2.0
