### ISSUE TITLE
Stubbing custom directives

### ISSUE THREAD

**Issue by keligijus** [jackmellis/vuenit#53]
I've got a custom directive: `Vue.directive('editor')` which it is used on an element in such way `<div v-editor></div>`

When testing I always get a warning _'[Vue warn]: Failed to resolve directive: editor (found in <Element>)'_. 

I did _vuenit.directive('editor')_, but this does not seem to be helping. How can I fix this?

**Comment by jackmellis** [comment]
Is this when you're attempting to test the directive itself or when you're testing a component that happens to use it?

The problem with globally registered directives/components/filters is that if you don't register them in your test environment, then Vue will get upset because it can't find them. The `stubDirectives` option can help to stub all *known* directives, i.e. locally or globally registered ones, but it cannot stub directives that Vue doesn't know about.

I will look at adding an option to stub specific directives in the same way as you can components and filters currently. An equivalent workaround would be to add a fake directive to the component instance before mounting...
```js
vuenit.component(c, {
  before(mountableComponent){
    mountableComponent.directives.editor = () => {}
  }
});
```
The `before` method lets you mess with the component definition without mutating the original component.

**Comment by keligijus** [comment]
Thanks so much for a quick reply. Your suggested solution works and is great! Thanks again!

edit: I had this problem when I was testing a component that uses the directive.

**Comment by jackmellis** [comment]
Added a `directives` option so you can easily stub directives:  
https://github.com/jackmellis/vuenit/releases/tag/0.5.0  

e.g.
```js
vuenit.mount(c, {
  directives : {
    editor : function(){ /* custom behaviour */ }
  }
});
```
or even more basic:
```js
vuenit.mount(c, {
  directives : ['editor']
});
```
